[package]
name = "udp"
version = "0.1.0"
authors = ["templain <grandmacks@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "udpecho"
path = "src/main.rs"

[dependencies]
pnet = "0.27"
anyhow = "1.0"
